import * as THREE from 'three';

const COLORS = {inferno:[0xff6320,0xffd45a],frost:[0x48cfff,0xc9ffff],plasma:[0xba44ff,0xff78dd],stardust:[0xffd76c,0xffffff]};
// One fixed GPU point pool, one instanced decal pool. No particle creates a draw call.
export class BallEffects {
 constructor(scene){
  this.count=360;this.budget=360;this.time=0;this.cursor=0;this.accumulator=0;this.skin='glacier';this.last=new THREE.Vector3();
  this.p=new Float32Array(this.count*3);this.v=new Float32Array(this.count*3);this.life=new Float32Array(this.count);this.max=new Float32Array(this.count);this.colors=new Float32Array(this.count*3);this.sizes=new Float32Array(this.count);
  this.geometry=new THREE.BufferGeometry();this.geometry.setAttribute('position',new THREE.BufferAttribute(this.p,3).setUsage(THREE.DynamicDrawUsage));this.geometry.setAttribute('color',new THREE.BufferAttribute(this.colors,3));this.geometry.setAttribute('aSize',new THREE.BufferAttribute(this.sizes,1).setUsage(THREE.DynamicDrawUsage));
  this.material=new THREE.ShaderMaterial({vertexColors:true,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uPixel:{value:600},uMode:{value:0},uTime:{value:0}},vertexShader:`attribute float aSize; varying float vSize; varying vec3 vColor; uniform float uPixel; void main(){vColor=color;vSize=aSize;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(aSize*uPixel/max(1.,-p.z),0.,48.);}`,fragmentShader:`varying float vSize;varying vec3 vColor;uniform float uMode;uniform float uTime;void main(){vec2 p=gl_PointCoord-.5;float r=length(p)*2.;float a=0.;vec3 c=vColor;if(uMode<.5){p.x+=sin(p.y*12.+uTime*9.)*.055;float taper=mix(.11,.43,1.-gl_PointCoord.y);r=length(vec2(p.x/taper,p.y*1.8));a=pow(max(0.,1.-r),1.1);c=mix(vec3(1.,.12,.005),vec3(1.,.9,.3),a);}else if(uMode<1.5){float diamond=abs(p.x)*1.9+abs(p.y)*1.1;a=pow(max(0.,1.-diamond*2.),.65);c=mix(vColor,vec3(1.),a*.8);}else{float core=exp(-dot(p,p)*80.);float rays=exp(-abs(p.x)*90.)+exp(-abs(p.y)*90.);a=(core+rays*.28)*max(0.,1.-r);c=vColor*1.6;}if(uMode<.5&&vSize<.10){a=pow(max(0.,1.-length(p)*2.),2.);c=vec3(1.,.6,.08);}if(a<.015)discard;gl_FragColor=vec4(c*1.4,a*.8);}`});
  this.points=new THREE.Points(this.geometry,this.material);this.points.frustumCulled=false;scene.add(this.points);
  this.trailGeo=new THREE.CircleGeometry(.14,12);this.trailMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.6,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2});this.trails=new THREE.InstancedMesh(this.trailGeo,this.trailMat,96);this.trails.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.trails.frustumCulled=false;scene.add(this.trails);this.trailAge=new Float32Array(96);this.trailPositions=Array.from({length:96},()=>new THREE.Vector3());this.trailRotations=Array.from({length:96},()=>new THREE.Quaternion());this.trailCursor=0;this.dummy=new THREE.Object3D();this.color=new THREE.Color();this.normal=new THREE.Vector3(0,1,0);
  this.smokeGeo=new THREE.BufferGeometry();this.smokeGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(96*3),3).setUsage(THREE.DynamicDrawUsage));this.smokeGeo.setAttribute('aLife',new THREE.BufferAttribute(new Float32Array(96),1).setUsage(THREE.DynamicDrawUsage));
  this.smokeMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uCold:{value:0}},vertexShader:'attribute float aLife;varying float vLife;void main(){vLife=aLife;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=(1.-aLife*.65)*280./max(1.,-p.z);}',fragmentShader:'varying float vLife;uniform float uCold;void main(){vec2 p=gl_PointCoord-.5;float r=length(p)*2.;float a=pow(max(0.,1.-r),2.)*sin(vLife*3.14159)*.2;gl_FragColor=vec4(mix(vec3(.15,.12,.18),vec3(.62,.9,1.),uCold),a);}'});
  this.smoke=new THREE.Points(this.smokeGeo,this.smokeMat);this.smoke.frustumCulled=false;scene.add(this.smoke);this.smokeLife=new Float32Array(96);this.smokeCursor=0;this.smokeBudget=96;
  this.shardGeo=new THREE.TetrahedronGeometry(.075);this.shardMat=new THREE.MeshStandardMaterial({color:0xabeeff,metalness:.65,roughness:.08,transparent:true,opacity:.85,emissive:0x24778e,emissiveIntensity:.15});this.shards=new THREE.InstancedMesh(this.shardGeo,this.shardMat,72);this.shards.frustumCulled=false;this.shards.count=0;scene.add(this.shards);this.shardData=[];
  this.reset();
 }
 reset(){this.shardData=[];if(this.shards)this.shards.count=0;this.smokeLife?.fill(0);this.life.fill(0);this.sizes.fill(0);this.trailAge.fill(0);this.last.set(999,999,999);for(let i=0;i<96;i++){this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.trails.setMatrixAt(i,this.dummy.matrix);}this.trails.instanceMatrix.needsUpdate=true;}
 setQuality(q){this.budget=q==='balanced'?180:360;this.smokeBudget=q==='balanced'?40:96;}
 setSkin(id){this.skin=id;this.material.uniforms.uMode.value=id==='inferno'?0:id==='frost'?1:2;this.smokeMat.uniforms.uCold.value=id==='frost'?1:0;this.reset();}
 shatter(position,normal){this.shardData=Array.from({length:64},()=>({p:position.clone(),v:new THREE.Vector3((Math.random()-.5)*4,(Math.random()-.5)*4,(Math.random()-.5)*4).addScaledVector(normal,1),life:1.4,angle:Math.random()*6}));this.shards.count=64;}
 burst(position,normal,count=100){for(let i=0;i<count;i++)this.spawn(position,normal,true);}
 spawn(position,normal,burst=false){const i=this.cursor++%this.budget,j=i*3;const angle=Math.random()*Math.PI*2,z=Math.random()*2-1,r=Math.sqrt(1-z*z)*.33;this.p[j]=position.x+Math.cos(angle)*r;this.p[j+1]=position.y+z*.33;this.p[j+2]=position.z+Math.sin(angle)*r;const speed=burst?3:.65;for(let a=0;a<3;a++)this.v[j+a]=(Math.random()-.5)*speed;this.v[j]+=normal.x*.65;this.v[j+1]+=normal.y*.65;this.v[j+2]+=normal.z*.65;this.life[i]=this.max[i]=.4+Math.random()*(burst?1:.7);this.color.setHex((COLORS[this.skin]||[0xff733c,0xffdb8e])[i%2]);this.color.toArray(this.colors,j);}
 update(dt,position,normal,grounded=true){
  this.time+=dt;this.material.uniforms.uTime.value=this.time;const palette=COLORS[this.skin];this.points.visible=!!palette||this.life.some(v=>v>0);this.accumulator+=dt*(palette?(this.skin==='inferno'?140:85)*(this.budget/360):0);while(this.accumulator>=1){this.accumulator--;this.spawn(position,normal);}
  for(let i=0;i<this.count;i++){this.life[i]=Math.max(0,this.life[i]-dt);this.sizes[i]=this.life[i]>0?(this.skin==='inferno'?(i%4===0?.085:.48):.16)*(this.life[i]/this.max[i]):0;for(let a=0;a<3;a++){const up=a===0?normal.x:a===1?normal.y:normal.z;this.v[i*3+a]+=dt*(up*(this.skin==='inferno'?1.3:.15)+Math.sin(this.time*4+i*.7+a*2)*.35);this.v[i*3+a]*=Math.exp(-dt*.65);this.p[i*3+a]+=this.v[i*3+a]*dt;}}
  const smoky=this.skin==='inferno'||this.skin==='frost';this.smoke.visible=smoky;
  if(smoky&&dt>0){const i=this.smokeCursor++%this.smokeBudget;this.smokeLife[i]=1;position.toArray(this.smokeGeo.attributes.position.array,i*3);}
  for(let i=0;i<96;i++){this.smokeLife[i]=Math.max(0,this.smokeLife[i]-dt*.65);this.smokeGeo.attributes.aLife.array[i]=this.smokeLife[i];for(let a=0;a<3;a++){const up=a===0?normal.x:a===1?normal.y:normal.z;this.smokeGeo.attributes.position.array[i*3+a]+=dt*(up*.7+Math.sin(this.time+i+a)*.13);}}
  this.smokeGeo.attributes.position.needsUpdate=true;this.smokeGeo.attributes.aLife.needsUpdate=true;
  if(this.shardData.length&&this.shardData.some(s=>s.life<=0))this.shardData=this.shardData.filter(s=>s.life>0);this.iceAccumulator=(this.iceAccumulator||0)+dt;
  if(this.skin==='frost'&&this.iceAccumulator>.13&&this.shardData.length<24){this.iceAccumulator=0;this.shardData.push({p:position.clone(),v:new THREE.Vector3(Math.sin(this.time*5),.5,Math.cos(this.time*5)).multiplyScalar(.6),life:.8,angle:this.time,size:.4});}this.shards.count=this.shardData.length;
  this.shardData.forEach((s,i)=>{s.life=Math.max(0,s.life-dt);s.v.addScaledVector(normal,-dt*4);s.p.addScaledVector(s.v,dt);this.dummy.position.copy(s.p);this.dummy.rotation.set(s.angle+this.time*5,s.angle+this.time*3,this.time);this.dummy.scale.set(.45,1.5,.7).multiplyScalar(Math.min(1,s.life*3)*(s.size||1));this.dummy.updateMatrix();this.shards.setMatrixAt(i,this.dummy.matrix);});if(this.shardData.length)this.shards.instanceMatrix.needsUpdate=true;
  for(const name of ['position','color','aSize'])this.geometry.attributes[name].needsUpdate=true;
  const surfaceSkin=this.skin==='inferno'||this.skin==='frost';if(surfaceSkin&&grounded&&position.distanceToSquared(this.last)>.018){const i=this.trailCursor++%96;this.trailAge[i]=3.5;this.trailPositions[i].copy(position).addScaledVector(normal,-.308);this.trailRotations[i].setFromUnitVectors(new THREE.Vector3(0,0,1),normal);this.last.copy(position);this.trails.setColorAt(i,this.color.setHex(palette[0]));this.trails.instanceColor.needsUpdate=true;}
  this.trails.visible=surfaceSkin;for(let i=0;i<96;i++){this.trailAge[i]=Math.max(0,this.trailAge[i]-dt);this.dummy.position.copy(this.trailPositions[i]);this.dummy.quaternion.copy(this.trailRotations[i]);this.dummy.scale.setScalar(Math.min(1,this.trailAge[i]/1.5));this.dummy.updateMatrix();this.trails.setMatrixAt(i,this.dummy.matrix);}this.trails.instanceMatrix.needsUpdate=true;
 }
 dispose(){for(const r of [this.geometry,this.material,this.trailGeo,this.trailMat,this.trails,this.smokeGeo,this.smokeMat,this.shardGeo,this.shardMat,this.shards])r.dispose();this.smoke.removeFromParent();this.shards.removeFromParent();this.points.removeFromParent();this.trails.removeFromParent();}
}

export function portalMaterial(){return new THREE.ShaderMaterial({side:THREE.DoubleSide,uniforms:{uTime:{value:0},uUnlocked:{value:0}},vertexShader:`varying vec2 vUv;varying vec3 vView;void main(){vUv=uv;vec4 p=modelViewMatrix*vec4(position,1.);vView=normalize(-p.xyz);gl_Position=projectionMatrix*p;}`,fragmentShader:`varying vec2 vUv;varying vec3 vView;uniform float uTime;uniform float uUnlocked;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
 void main(){vec2 p=(vUv-.5)*2.;float r=length(p);if(r>1.)discard;vec2 q=p+vView.xy*.15;float a=atan(q.y,q.x);float vortex=sin(a*5.-r*13.+uTime*1.4);vec3 sky=mix(vec3(.025,.025,.18),vec3(.16,.3,.72),q.y*.5+.5);float horizon=-.32+sin(q.x*5.+uTime*.1)*.12;sky=mix(sky,vec3(.055,.1,.24),1.-smoothstep(horizon,horizon+.03,q.y));float moon=1.-smoothstep(.17,.18,length(q-vec2(.25,.28)));sky+=vec3(.5,.9,1.)*moon;vec2 stars=floor((q+uTime*.003)*70.);sky+=vec3(pow(hash(stars),90.))*.7;float ring=pow(r,7.)*(.6+.4*vortex);sky+=vec3(.08,1.1,.7)*ring;vec3 locked=vec3(.12,.08,.22)+vec3(.35,.13,.5)*pow(abs(sin(q.x*15.)*sin(q.y*15.)),12.);gl_FragColor=vec4(mix(locked,sky,uUnlocked),1.);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});}
